# docker-compose.dev.yml
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: pnpm --filter @kalsumed/backend dev
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app:cached
    ports:
      - "3000:3000"
    env_file:
      - .env.dev

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    command: pnpm --filter @kalsumed/frontend dev
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app:cached
    ports:
      - "5173:5173"
    env_file:
      - .env.dev

  gateway:
    build:
      context: .
      dockerfile: docker/gateway/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps/gateway/traefik/certificates:/certificates

  database:
    image: postgres:15-alpine
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    env_file:
      - .env.dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file:
      - .env.dev
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  db-data:
  redis-data:
  rabbitmq-data:

