services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile.dev
    command: sh -c "pnpm install --filter @kalsumed/backend... && pnpm --filter @kalsumed/backend dev"
    working_dir: /usr/src/apps/backend
    volumes:
      - ./:/usr/src:cached
      - backend_node_modules:/usr/src/apps/backend/node_modules
      - backend_dist:/usr/src/apps/backend/dist
    ports:
      - "3000:3000"
    env_file:
      - .env.dev

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile.dev
    command: sh -c "pnpm install --filter @kalsumed/frontend... && pnpm --filter @kalsumed/frontend dev"
    working_dir: /usr/src/apps/frontend
    volumes:
      - ./:/usr/src:cached
      - frontend_node_modules:/usr/src/apps/frontend/node_modules
    ports:
      - "5173:5173"
    env_file:
      - .env.dev

  gateway:
    build:
      context: .
      dockerfile: docker/gateway/Dockerfile
    command: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps/gateway/traefik/certificates:/certificates

  database:
    image: postgres:15-alpine
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    env_file:
      - .env.dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file:
      - .env.dev
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  db-data:
  redis-data:
  rabbitmq-data:
  frontend_node_modules:
  backend_node_modules:
  backend_dist: