version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: kalsumed-postgres-container-instance
    environment:
      POSTGRES_USER: kalsumed-db-user
      POSTGRES_PASSWORD: d9ds8fdDSF
      POSTGRES_DB: kalsumed-db
    ports:
      - "5432:5432"
    volumes:
      - kalsumed-db:/var/lib/postgresql/data

volumes:
  kalsumed-db:
