# .github/workflows/build-on-merge.yml

name: Build and Test Spring Boot Application with JDK 21

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - 'feature/**'

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: 'test'  # Set the active profile to 'test'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Grant Execute Permission for Gradlew
        run: chmod +x ./gradlew

      - name: Verify Java Version
        run: java -version

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: build/libs/*.jar

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/reports/tests/test
