name: Build & Health-Check Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-unit:
    name: Lint & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test:unit

  test:
    name: Build & Health-Check
    needs: lint-and-unit    
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate backend and frontend .env.dev from templates and Secrets
        run: |
          mkdir -p apps/backend apps/frontend

          # Backend
          cp apps/backend/.env.template apps/backend/.env.dev
          sed -i "s|POSTGRES_HOST=.*|POSTGRES_HOST=postgres|" apps/backend/.env.dev
          sed -i "s|POSTGRES_USER=.*|POSTGRES_USER=${{ secrets.POSTGRES_USER }}|" apps/backend/.env.dev
          sed -i "s|POSTGRES_PASSWORD=.*|POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}|" apps/backend/.env.dev
          sed -i "s|POSTGRES_DB=.*|POSTGRES_DB=${{ secrets.POSTGRES_DB }}|" apps/backend/.env.dev
          sed -i "s|DATABASE_HOST=.*|DATABASE_HOST=database|" apps/backend/.env.dev
          sed -i "s|REDIS_PASSWORD=.*|REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}|" apps/backend/.env.dev        
          sed -i "s|RABBITMQ_USER=.*|RABBITMQ_USER=${{ secrets.RABBITMQ_USER }}|" apps/backend/.env.dev
          sed -i "s|RABBITMQ_PASSWORD=.*|RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}|" apps/backend/.env.dev          
          sed -i "s|JWT_SECRET=.*|JWT_SECRET=${{ secrets.JWT_SECRET }}|" apps/backend/.env.dev
          sed -i "s|NODE_ENV=.*|NODE_ENV=${{ secrets.NODE_ENV }}|" apps/backend/.env.dev

          # Frontend
          cp apps/frontend/.env.template apps/frontend/.env.dev
          sed -i "s|VITE_API_BASE_URL=.*|VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}|" apps/frontend/.env.dev

      - name: Dump the backend .env.dev
        run: |
          echo "--- apps/backend/.env.dev ---"
          cat apps/backend/.env.dev
          echo "-----------------------------"          

      - name: Build & start dev stack
        run: docker compose --env-file apps/backend/.env.dev -f docker-compose.dev.yml up -d --build

      - name: Wait for backend health endpoint
        run: |
          for i in {1..60}; do
            HTTP=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/api/health) || true
            if [ "$HTTP" = "200" ]; then
              echo "✅ Health check passed"
              exit 0
            fi
            echo "⏳ waiting for health... ($i/60)"
            sleep 2
          done
          echo "❌ Health endpoint never became ready"

          echo "\n📌 Docker compose logs for debugging:"
          docker compose -f docker-compose.dev.yml logs backend database

          exit 1

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Assert health payload
        run: |
          curl -s http://localhost:3000/api/health | jq .
          curl -s http://localhost:3000/api/health \
            | jq -e '
                .status                     == "ok" and
                .info.database.status       == "up" and
                .info.redis.status          == "up"
              '

      - name: Tear down dev stack
        if: always()
        run: docker compose -f docker-compose.dev.yml down -v --remove-orphans
